FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build

WORKDIR /src

COPY . .

ARG ENV

WORKDIR /src/PesquisaSatisfacaoSenacEducacional
RUN dotnet publish PesquisaSatisfacaoSenacEducacional.csproj -c Release /p:EnvironmentName=${ENV} -o /app/out

FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /app

ENV TZ=America/Sao_Paulo
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

COPY --from=build /app/out .

# Habilita o stdoutLogEnabled no web.config
RUN sed -i 's/stdoutLogEnabled="false"/stdoutLogEnabled="true"/g' ./web.config

# ENTRYPOINT ["dotnet", "PesquisaSatisfacaoSenacEducacional.dll"]
