FROM node:16-alpine

RUN apk add --no-cache tzdata git

ENV TZ=America/Sao_Paulo
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 8080

# Run the application
CMD ["npm", "run", "serve"]
